#+title: 2023年の振り返り(その他編)
#+date: 2024-01-04T14:42:17+09:00
#+Categories[]: COMP
#+Tags[]: Keyboard, 3Dprinter 

* 自作キーボード

これが2022年末ということは、ほぼ1年進捗なしということになる。

{{< tweet user="nekomimist" id="1601574904968908800" >}}                                        

2023/1に当時最新のqmkに合わせて自分のキーボードのソースを書きかえたりしたけれど、それも1年前なので、また追随しなければいけないが、qmk側の都合による変更であって、自分のキーボードの機能が不足しているわけではないので、どうもやる気が出ない。

2024年は2つくらいキーボードのネタがある。

** nekonos1の改版

上のpostはSU120で作ったものだが、同じレイアウトで自分に設計した基板に変えたい。Adafruit KB2040が2つ手元にあるのでこれを使う。まあ、あまりピン配置はPro Microと変わらんので、Pro Microでも作れるようにはする。

3Dプリンタケースと合わせて設計したいので、やる事が多くてやる元気がでるかどうかは不明。

** nekonote1

昔te96で作った [[https://twitter.com/nekomimist/status/1349289225011662850][nekonote0]]の改版。18x16ピッチを18x17ピッチに変える。BLE Micro Proで作るくらいな感じで。
薄さと丈夫さを兼ねそろえたいと思うとケースは悩ましいが、基板サンドイッチ構造でいいのかも。


* 3Dプリンタ 

** KP3S 1.0をSnakeOilXY-3Sに改造した。

これが、

{{< tweet user="nekomimist" id="1619154955545485317" >}}                                        

こうなった。

{{< tweet user="nekomimist" id="1700330614963191968" >}}                                        

カッコいいし、安定度も高く満足度は高い。

** VORON 0.1

VORON 0.1はSherpa Miniの部品破損トラブルがあったのを直したのみ。
構成がシンプルなのでExtruderまわりの断線とパーツ破断以外はほぼトラブらないよい子。

{{< tweet user="nekomimist" id="1704510705364258937" >}}                                        

** VORON Trident

2022年末にCAN toolheadてそこに由来するトラブルは1年間特に発生しなかった。

{{< tweet user="nekomimist" id="1606564633846120448" >}}                                        

2022年10月頃にやったUnklickyNG改造のほうは、ちょっといろいろトラブルがあった。

{{< tweet user="nekomimist" id="1695419563641590086" >}}                                        

このトラブルでCNC TAP化しようと思って部品調達までしたのだが、
ヘッドまわりの複雑度が上がってトラブルったときに切り分けが難しくなりすぎそうなのを嫌って、
国内調達のまともなN52ネオジムでUnklickのマウント側作りなおしたら磁力が段違いで安定するようになった。

** 2024年の抱負

SnakeOilXY-3SとVORON 0.1は特になし。VORON 0.1はシンプルさゆえの安定度とメンテ性を捨てたくない。[[https://github.com/zruncho3d/tri-zero][Tri-Zero]]用の部品はだいぶ前に買ってしまってはいるのだけれど。

VORON Tridentもまあ特に急ぐネタはなし。[[https://github.com/DW-Tas/Klicky-00][Klicky-00]]は少し気になるけれど。

